name: flutter_vision_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  opencv_dart: ^2.1.0
  pdf: ^3.11.3
  image: ^4.5.4
  open_file: ^3.5.11
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.11.0

# We use it to include only the modules of OpenCV that we actually need,
# instead of pulling in/building the entire OpenCV library with many unused features.
# This keeps the integration lighter (smaller binaries and faster builds) while still
# supporting our document-scanning pipeline.
hooks:
  user_defines:
    dartcv4:
      include_modules:
        # contains the document-scanner pipeline building blocks
        - imgproc
        # decode/encode images (imdecode/imencode) from/to JPG/PNG bytes.
        - imgcodecs

flutter:
  uses-material-design: true
